version: 2

anchors:
  - &pl_matches_structure
    columns:
      - name: id
        description: "Primary key - match ID"
        data_tests:
          - unique
          - not_null
      - name: utcDate
        description: "Date at which match started - in UTC"
        data_tests:
          - not_null
      - name: status
        description: "Status of the match"
        data_tests:
          - accepted_values:
              arguments:
                values: ['SCHEDULED', 'LIVE', 'IN_PLAY', 'PAUSED', 'FINISHED', 'POSTPONED', 'SUSPENDED', 'CANCELLED']
      - name: matchday
        description: "Integer - a matchday at which the fixture took place"
        data_tests:
          - not_null
      - name: stage
        description: "Which part of the season the match took place at"
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['REGULAR_SEASON']
      - name: group
        description: "Allows filtering for groupings in a competition. Always null"
      - name: lastUpdated
        description: "Timestamp at which the match info has been updated most recently. Timezone: UTC"
        data_tests:
          - not_null
      - name: referees
        description: "Nested object. Contains id, name and nationality of the referee. String type."
      - name: area_id
        description: "ID for the area (ex. Country) where match took place in"
      - name: area_name
        description: "Name for the area (ex. Country) where match took place in"
      - name: area_code
        description: "Code for the area (ex. Country) where match took place in"
      - name: area_flag
        description: "Link to flag for the area (ex. Country) where match took place in"
      - name: competition_id
        description: "ID of the competition"
        data_tests:
          - not_null
      - name: competition_name
        description: "Name of the competition"
        data_tests:
          - not_null
      - name: competition_code
        description: "Code of the competition"
        data_tests:
          - not_null
      - name: competition_type
        description: "Type of the competition (League, Cup etc.)"
        data_tests:
          - not_null
      - name: competition_emblem
        description: "Logo of the competition"
      - name: season_id
        description: "Identifier of the season for a competition"
        data_tests:
          - not_null
      - name: season_startDate
        description: "Start date of the competition. YYYY-MM-DD"
      - name: season_endDate
        description: "End date of the competition. YYYY-MM-DD"
      - name: season_currentMatchday
        description: "Integer - the matchday of the competition at the time of last update date. If season hasn't started yet, it defaults to 1."
      - name: season_winner
        description: "Winner of the whole competition for a specified season."
      - name: homeTeam_id
        description: "ID of the match's home team."
        data_tests:
          - not_null
      - name: homeTeam_name
        description: "Full name of the match's home team."
        data_tests:
          - not_null
      - name: homeTeam_shortName
        description: "Abbreviated name of the match's home team."
      - name: homeTeam_tla
        description: "Three-Letter Acronym of the match's home team."
        data_tests:
          - not_null
      - name: homeTeam_crest
        description: "Link to creast of the home team."
      - name: awayTeam_id
        description: "ID of the match's away team."
        data_tests:
          - not_null
      - name: awayTeam_name
        description: "Full name of the match's away team."
        data_tests:
          - not_null
      - name: awayTeam_shortName
        description: "Abbreviated name of the match's away team."
      - name: awayTeam_tla
        description: "Three-Letter Acronym of the match's away team."
        data_tests:
          - not_null
      - name: awayTeam_crest
        description: "Link to creast of the away team."
      - name: score_winner
        description: "The resolution of the match. Indicates the winning team or lack thereof."
        data_tests:
          - accepted_values:
              arguments:
                values: ['AWAY_TEAM', 'HOME_TEAM', 'DRAW']
      - name: score_duration
        description: "Indicates whether the score was reached in regulation or not. For PL, only REGULAR is possible"
        data_tests:
          - accepted_values:
              arguments:
                values: ['REGULAR']
      - name: score_fullTime_home
        description: "Integer. Number of goals scored by home team at fulltime."
      - name: score_fullTime_away
        description: "Integer. Number of goals scored by away team at fulltime."
      - name: score_halfTime_home
        description: "Integer. Number of goals scored by home team at half-time."
      - name: score_halfTime_away
        description: "Integer. Number of goals scored by away team at half-time."
      - name: odds_msg
        description: "Odds for the match. Not available at current API plan."

  - &pl_teams_structure
    columns:
      - name: id
        description: "Primary key - team ID"
        data_tests:
          - unique
          - not_null
      - name: name
        description: "Full name of the team."
        data_tests:
          - unique
          - not_null
      - name: shortName
        description: "Abbreviated name of the team."
        data_tests:
          - unique
          - not_null
      - name: tla
        description: "Three-Letter Acronym of the team."
        data_tests:
          - unique
          - not_null
      - name: crest
        description: "Link to the crest of the team."
      - name: address
        description: "Full address of the team's stadium."
      - name: website
        description: "Team's official site URL."
      - name: founded
        description: "Year when team was founded."
      - name: venue
        description: "Name of the team's stadium."
      - name: runningCompetitions
        description: "String. JSON formatted list of competitions the team is competing in."
      - name: squad
        description: "String. JSON formatted list of team's full squad (includes name, position, DOB and nationality)."
      - name: staff
        description: "String. JSON formatted list of team's staff."
      - name: lastUpdated
        description: "Timestamp at which the match info has been updated most recently. Timezone: UTC"
        data_tests:
          - not_null
      - name: area_id
        description: "ID for the area (ex. Country) where match took place in"
      - name: area_name
        description: "Name for the area (ex. Country) where match took place in"
      - name: area_code
        description: "Code for the area (ex. Country) where match took place in"
      - name: area_flag
        description: "Link to flag for the area (ex. Country) where match took place in"
      - name: coach_id
        description: "ID for the team's coach."
      - name: coach_firstName
        description: "Team's coach first name."
      - name: coach_lastName
        description: "Team's coach last name."
      - name: coach_name
        description: "Team's coach full name."
      - name: coach_dateOfBirth
        description: "Team's coach DOB."
      - name: coach_nationality
        description: "Team's coach nationality."
      - name: coach_contract_start
        description: "Date from which coach started working with the team."
      - name: coach_contract_until
        description: "The date until which the coach's contract is valid."

  - &pl_top_scorers_structure
    columns:
      - name: playedMatches
        description: "Integer. Number of matches played in a season."
        data_tests:
          - not_null
      - name: goals
        description: "Integer. Number of goals scored in a season."
      - name: assists
        description: "Float. Number of assist in a season."
      - name: penalties
        description: "Float. Number of penalties scored in a season."
      - name: player_id
        description: "Unique ID of the player."
        data_tests:
          - unique
          - not_null
      - name: player_name
        description: "Full name of the player."
        data_tests:
          - not_null
      - name: player_firstName
        description: "First name of the player. Can be null"
      - name: player_lastName
        description: "Last name of the player."
        data_tests:
          - not_null
      - name: player_dateOfBirth
        description: "DOB of the player."
        data_tests:
          - not_null
      - name: player_nationality
        description: "Nationality of the player."
        data_tests:
          - not_null
      - name: player_section
        description: "Main line at which player plays at."
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Midfield', 'Offence', 'Defence', 'Centre-Forward']
      - name: player_position
        description: "Main position of the player."
      - name: player_shirtNumber
        description: "Shirt number of the player."
      - name: player_lastUpdated
        description: "Timestamp at which the player info has been updated most recently. Timezone: UTC"
        data_tests:
          - not_null
      - name: team_id
        description: "Player's team ID."
        data_tests:
          - not_null
      - name: team_name
        description: "Full name of the team player plays at."
        data_tests:
          - not_null
      - name: team_shortName
        description: "Abbreviated name of the  team player plays at."
        data_tests:
          - not_null
      - name: team_tla
        description: "Three-Letter Acronym of the  team player plays at."
        data_tests:
          - not_null
      - name: team_crest
        description: "Link to the crest of the  team player plays at."
      - name: team_address
        description: "Full address of the player's team stadium."
      - name: team_website
        description: "Player's team official site URL."
      - name: team_founded
        description: "Year when player's team was founded."
      - name: team_clubColors
        description: "Main colors of the player's team."
      - name: team_venue
        description: "Stadium name of the player's team."
      - name: team_lastUpdated
        description: "Timestamp at which the team info has been updated most recently. Timezone: UTC"

sources:

  - name: pl_data
    description: >
      Raw Premier League data loaded from football-data.org.
      Contains match, team and top-scorer data starting from
      the 2024/2025 season, as well as historical season winner data.

    database: jga-sandbox
    schema: bronze

    tables:

      - name: football_data_pl_matches_2024_25
        description: "Premier League matches for the 2024/2025 season."
        <<: *pl_matches_structure

      - name: football_data_pl_matches_2025_26
        description: "Premier League matches for the 2025/2026 season."
        <<: *pl_matches_structure

      - name: football_data_pl_matches_2026_27
        description: "Premier League matches for the 2026/2027 season."
        <<: *pl_matches_structure

      - name: football_data_pl_teams_2024_25
        description: "Premier League teams for the 2024/2025 season."
        <<: *pl_teams_structure

      - name: football_data_pl_teams_2025_26
        description: "Premier League teams for the 2025/2026 season."
        <<: *pl_teams_structure

      - name: football_data_pl_teams_2026_27
        description: "Premier League teams for the 2026/2027 season."
        <<: *pl_teams_structure

      - name: football_data_pl_top_scorers_2024_25
        description: "Premier League top 100 scorers for the 2024/2025 season."
        <<: *pl_top_scorers_structure

      - name: football_data_pl_top_scorers_2025_26
        description: "Premier League top 100 scorers for the 2025/2026 season."
        <<: *pl_top_scorers_structure

      - name: football_data_pl_top_scorers_2026_27
        description: "Premier League top 100 scorers for the 2026/2027 season."
        <<: *pl_top_scorers_structure

      - name: football_data_pl_winners_bronze
        description: "Contains information on PL winners (detailed info available from 1990/1991 season)."
        columns:
          - name: id
            description: "Primary key - season ID"
            data_tests:
              - unique
              - not_null
          - name: startDate
            description: "Start of the season date. YYYY-MM-DD"
            data_tests:
              - not_null
          - name: endDate
            description: "End of the season date. YYYY-MM-DD"
            data_tests:
              - not_null
          - name: currentMatchday
            description: "Current matchday of the season. 1 if season hasnt started. Last matchday if season ended (38 or 42)"
          - name: winner
            description: "Always null. This field should not be referred to as the winner of the competition"
          - name: winner_id
            description: "Float. ID of the team that won a competition in that season."
          - name: winner_name
            description: "Full name of the team that won a competition in that season."
          - name: winner_shortName
            description: "Short name of the team that won a competition in that season."
          - name: winner_tla
            description: "Three-Letter Acronym of the team that won a competition in that season."
          - name: winner_crest
            description: "Link to the crest of the team that won a competition in that season."
          - name: winner_address
            description: "Full address of the winner's stadium."
          - name: winner_website
            description: "Winner's official site URL."
          - name: winner_founded
            description: "Year when winning team was founded."
          - name: winner_clubColors
            description: "Main colors of the winning team."
          - name: winner_venue
            description: "Stadium name of the winning team."
          - name: winner_lastUpdated
            description: "Timestamp at which the winner info has been updated most recently. Timezone: UTC. Please be aware that this source has not been updated since 2022."
